theme: jekyll-theme-minimal
font:
  enable: true

  # Uri of fonts host. E.g. //fonts.googleapis.com (Default)
  host: "https://fonts.google.com/"

  # Global font settings used on <body> element.
  global: 
    # external: true will load this font family from host.
    external: true
    family: "Open Sans"

#remote_theme: "mmistakes/so-simple-theme@3.2.0"
